#!/bin/bash

GIT_REPO=https://github.com/GavinNL/cppnew
GIT_LOCAL_REPO=$HOME/.cache/cppnew

TEMPLATE_LOCATION=$HOME/Projects/cppnew/templates

TEMPLATE=$1
DIR_NAME=$2

if [ ! -d ${GIT_LOCAL_REPO} ]; then
    echo "Cloning all templates to: ${GIT_LOCAL_REPO}"
    git clone ${GIT_REPO} ${GIT_LOCAL_REPO}
fi


function list_templates() {

for f in ${TEMPLATE_LOCATION}/*; do
    if [ -f ${f}/DESCRIPTION ]; then
        # Will not run if no directories are available
        echo "   " $(basename ${f} suffix)  -  $(cat ${f}/DESCRIPTION)
    fi
done

}


function new_proj() {
   template=$1
}

function template_exists()
{
    if [[ -f ${TEMPLATE_LOCATION}/$1/DESCRIPTION ]]; then
        return 0
    fi
    return 1
}

if [[ "$TEMPLATE" == "" || "$DIR_NAME" == "" ]]; then
    echo ""
    echo "Templates:"
    echo ""
    list_templates
    echo ""
    exit 1
fi

if [ -e ${PWD}/${DIR_NAME} ]; then
    echo ${PWD}/${DIR_NAME} exists. Cannot create template
    exit 1
fi


if [[ "$TEMPLATE" == "" || "$DIR_NAME" == "" ]]; then

    list_templates

else

    if ! template_exists $TEMPLATE; then

        echo "Template, ${TEMPLATE} does not exist"

    else

        cp  -r ${TEMPLATE_LOCATION}/$1 ${DIR_NAME}
        rm  ${DIR_NAME}/DESCRIPTION

    fi

fi
